project_name: gih
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/main.go
    binary: gih
    ldflags: 
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto