name: golangci-lint
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.24]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v7
