name: unittest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run_test:
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Run test
        run: go test -v -race ./...
