name: unittest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run_test:
    strategy:
      matrix:
        go-version: [1.24]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0

      - name: Run test
        run: go test -v -race ./...
